### ISSUE TITLE
Minimap Border forced to show

### ISSUE THREAD

**Issue by Musouv** [Ketrel/MinimapButtonFrame-Redux#10]
The border for minimaps appears to be forced to show by MMBF. I use Sexymap to change my minimap to a square layout, while hiding the default border. When MMBF is on, it forces the border to always show despite this.

Reproduction:
Enable Sexymap, go to options - borders, check "Hide default border". Border is hidden as expected.
Enable MMBF - border now always shows
Disable MMBF - border is back to being hidden.

**Comment by Ketrel** [comment]
Is this the same issue being described in #8 ?

If so, that actually gives me a starting place.

**Comment by Ketrel** [comment]
For reference I'm fairly certain this has something to do with how they're being grabbed, I have not been able to track down how to remove the borders from gathered buttons so far.

If you're familiar, always feel free to submit pull requests.

**Comment by Musouv** [comment]
No, it's a different issue. The minimap border is the new border added in the Dragonflight UI. It looks like this:
![image](https://user-images.githubusercontent.com/15886320/200203922-e7c17fa4-ccdb-43f6-924e-95f17d265f16.png)
when it should look like this
![image](https://user-images.githubusercontent.com/15886320/200203799-5eda10f9-f33a-4be2-96a6-d44fefe9ca43.png)

**Comment by Ketrel** [comment]
What version of SexyMap and Minimap Button Frame Redux are you using?

I can't replicate this with MBF-R 2.0.5 and SexyMap 10.0.2
![Wow_2022-11-06_19-27-20](https://user-images.githubusercontent.com/1002607/200204145-099a90b9-124a-48ef-b862-39c742653d76.png)

**Comment by Musouv** [comment]
I've narrowed it down, oddly it seems to happen with these 4 addons enabled, but if any of them are disabled, then it behaves correctly:
MBF-R 2.0.5
Sexymap 10.0.5
Details DF.Wrath.10259.146
Outfitter (Equipment Manager - fan fixes) 10.0.0v5
However, it doesn't seem to happen on a newly created character, so it may be a profile issue.
