### ISSUE TITLE
MBF isn't picking up icon for DEJUNK

### ISSUE THREAD

**Issue by karpana** [Ketrel/MinimapButtonFrame-Redux#11]
I'm not sure if this needs to be filed as an issue here or over with [DEJUNK](https://www.curseforge.com/wow/addons/dejunk), but I figured since I'd start here, since it's MBF's role to "pickup icons".

Specifically, it looks like MBF is detecting the DEJUNK icon, as in my setup, it's giving it the square icon profile I prefer.  But MBF doesn't seem to want to keep it in the frame, even though there's clearly a spot for it (see second screen cap, second row, middle icon)

![image](https://user-images.githubusercontent.com/15716173/200416158-6867449d-0933-4473-b38b-92d3ee7ec417.png)

![image](https://user-images.githubusercontent.com/15716173/200416186-626b52fc-3012-4f1d-97f7-52ddf80482a9.png)

**Comment by Ketrel** [comment]
I'm not familiar with that addon or how it manages its button, but did you hover over it and run the command `/mbf add` while the mouse is over the button? Does it stay grabbed if you do that?

**Comment by karpana** [comment]
- I'll give it a try tomorrow.

**Comment by karpana** [comment]
Now that the US realms are back up, I figured I'd give this a try.
I ran `/mbf add` while hovering the button.

Message was produced in the chat
`Minimap Button Frame: Cannot add.  Protected or already included!  :  LibDBIcon10_Dejunk`

I took a look in the Protected Items list in the MBF config and it's not showing in the list

I also took a look in the Button Override section and it's not showing there either.

**Comment by moody** [comment]
Confirmed that this is an issue with Dejunk. I was calling `LibDBIcon:Show()` on every update which caused the button to be endlessly repositioned.

**Comment by Ketrel** [comment]
Looks like Dejunk has a commit that's intended to fix this.  I'll wait to see the result of that before updating this :)

**Comment by karpana** [comment]
Thank you @moody and @Ketrel

**Comment by Ketrel** [comment]
I haven't heard anything back on this.  I'm assuming at this point that fixed it.

Please reopen this if not.
