### ISSUE TITLE
is Ace3 required to run MBF?

### ISSUE THREAD

**Issue by MystbornGames** [Ketrel/MinimapButtonFrame-Redux#12]
Currently Ace3 isn't updated for DF—the current version is  9.2.7. This doesn't seem to be causing any issues (yet, at least I don't think so) but I'm wondering if it's fully required to run MBF properly, or if there's an alternative in case it doesn't get updated. 

A lot of my mods are still pretty borked from the 10.0 changes so I've been going through and trying to get rid of anything I don't absolutely need. Thank you

**Comment by Ketrel** [comment]
Ace3 is required, but most current Ace3 release [Release-r1294](https://www.wowace.com/projects/ace3/files/4040413) (Oct 22, 2022) is included.  You do not need it installed as a standalone addon.
