### ISSUE TITLE
Lua error, broken on wotlk classic

### ISSUE THREAD

**Issue by ssateneth** [Ketrel/MinimapButtonFrame-Redux#14]
using 2.0.5 on the newest wotlk classic build 3.4.1

Message: .../MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua:273: attempt to index field 'ZoomIn' (a nil value)
Time: Tue Jan 17 17:49:33 2023
Count: 1
Stack: .../MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua:273: attempt to index field 'ZoomIn' (a nil value)
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:273: in main chunk

Locals: LibStub = <table> {
 NewLibrary = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibStub/LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibStub/LibStub.lua:46
 GetLibrary = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/LibStub/LibStub.lua:36
 libs = <table> {
 }
}
L = <table> {
 Sort By Rows = "Sort By Rows"
 ICONADDTITLE_DESC = "Add Protected Item"
 OVERRIDEDESC_DESC = "Buttons the MBF thinks are Minimap Icons but are really buttons."
 Collect Button = "Collect Button"
 No Parent = "No Parent"
 debug = "debug"
 MBFANCHOR_DESC = "The corner of the MBF window that the frame will grow from."
 Nothing = "Nothing"
 CURRENTEXCEPTIONS_DESC = "Current Protected Items exceptions"
 Alphabetical = "Alphabetical"
 MBF_SLASH_Detail6 = "show - Shows the main MBF screen."
 Bottom Right = "Bottom Right"
 MBF_SLASH_Detail5 = "config - Shows the configuration screen."
 Parent = "Parent"
 Display Settings = "Display Settings"
 OPACITY_DESC = "Set the opacity of the frame."
 BUTTONTEXT_DESC = "Text to show on button"
 MBF_ERR6 = "Button not ready to be added.  Please Retry."
 UP = "UP"
 MBF_ERR2 = "Only buttons on the MinimapButtonFrame can be removed from it."
 MBF_TOOLTIP_ROLLUP = "Left-Click + drag to move MBF
Right-click to Hide/Show the frame"
 MBF_ERR4 = "Cannot add.  Protected or already included!"
 Exclude Queue Button = "Exclude Queue Button"
 Unnamed Object = "Unnamed Object"
 MBF_SLASH_Detail3 = "remove - removes a gathered button from the frame"
 Display = "Display"
 Grow Buttons Up = "Grow Buttons Up"
 No New Mail = "No New Mail"
 UP_DESC = "Move the selected minimap button's order up"
 MBF_ERR5 = "Error Removing Child Events from storage."
 Opacity = "Opacity"
 Top Right = "Top Right"
 remove = "remove"
 ZOOM_DESC = "Hide the Blizzard Minimap Zoom Buttons"
 Gathering Settings = "Gathering Settings"
 VOICECHAT_DESC = "Hide the Blizzard Voice Chat Button"
 MBF_TOOLTIP_FULL = "Left-Click to Hide/Show the frame
Shift-click to show the config screen
Right-click + drag to move the button"
 Hide World Map = "Hide World Map"
 TRACKING_DESC = "Hide the Blizzard Tracking Button"
 COLLECT2_DESC = "Collect the Blizzard Minimap Buttons"
 LOCKED_DESC = "Toggles whether the MBF frame is locked."
 All = "All"
 ICONADD_DESC = "The generalized name of the Item to be protected."
 Sorting Settings = "Sorting Settings"
 MBF_TOOLTIP_SMALL = "Shift-click to show the config screen"
 GATHERDESC2_DESC = "Settings for the Blizzard Minimap Buttons"
 Button Override = "Button Override"
 WORLDMAP_DESC = "Hide the Blizzard World Map Button"
 DRAGLOCKED_DESC = "Prevent the button and frame from being moved."
 ICONREMOVE_DESC = "Removes the selected Protected Item from the exceptions"
 Show Minimap Button = "Show Minimap Button"
 SHOWBUTTON_DESC = "Show the MBF Minimap Button."
 COLOR_DESC = "Chooses the background color for MBF."
 MBF_SLASH_Detail8 = "reload - Re-applies the texture.  This fixes the blackend icons."
 MBF_ERR1 = "Error Removing Button from Storage"
 Hide when Locked = "Hide when Locked"
 Exceptions Settings = "Exceptions Settings"
 MBF Anchor = "MBF Anchor"
 ALTTITLE_DESC = "Alt Title Bar Location"
 MBF_ERR7 = "Button or Object does not exist."
 Blizzard = "Blizzard"
 CALENDAR_DESC = "Hide the Blizzard Calendar Icon"
 Hide Tracking = "Hide Tracking"
 GATHERDESC1_DESC = "Settings for the MBF Minimap Button"
 MBF_LDB_TOOLTIP = "Left-Click to Hide/Show the frame
Shift-click to show the config screen"
 GROWUP_DESC = "Fills the frame with buttons from the bottom up."
 Protecte

**Comment by Ketrel** [comment]
This addon is Retail only.  
I don't play Classic and have no way to develop or test on Classic.  
(I haven't tried, but it's possible one of the older versions of the original addon (not Redux) might work on Classic, but that's a shot in the dark on my part.)

**Comment by ssateneth** [comment]
Well I poked around... Seems the Minimap frame doesn't exist anymore, and checking the framexml I found that the frames that this addon is looking for has been renamed.

Change line 273 from

minimapZoomInShow   = Minimap.ZoomIn.Show,

to

minimapZoomInShow   = MinimapZoomIn.Show,

and line 274 from 

minimapZoomOutShow  = Minimap.ZoomOut.Show,

to

minimapZoomOutShow  = MinimapZoomOut.Show,

No more errors and the addon works as intended. WOTLK Classic got migrated to dragonflight codebase so I'm surprised that you aren't running into this error on Dragonflight, unless the minimap zoom in/out function is significantly different between the two versions and Blizzard just added back in those functions under a different name

**Comment by Ketrel** [comment]
Unfortunately, that will break it for Dragonflight.  
This addon is Retail only.

It's also open source, so if you'd like to create a fork supporting Classic, go right ahead, but as I cannot test it, I can't accept any changes in support of classic into this version, especially those I know for sure will break the addon for retail.
