### ISSUE TITLE
Error 2/5/23

### ISSUE THREAD

**Issue by DeathRisings** [Ketrel/MinimapButtonFrame-Redux#15]
Message: .../MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua:1826: attempt to index global 'MiniMapMailFrame' (a nil value)
Time: Sun Feb  5 19:10:09 2023
Count: 1
Stack: .../MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua:1826: attempt to index global 'MiniMapMailFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1826: in function `updatePositions'
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1862: in function `?'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: 

Not sure if it is Minimap button or Ace 3 problem. I just downloaded the latest Minimap zip file before getting this.

**Comment by Ketrel** [comment]
This looks like the same issue as #13 

I have continuously been unable to reproduce this.

The only thing I can think of to mention is both your error and the one in #13 mention an AceTimer-3.0 that's not the one included with this addon.  Since your Ace3 looks like it's directly in the addons folder, Can you share the Ace3.toc file contents here.

BTW it's a lot more readable for code like this if you wrap it like this (those are back ticks followed by two spaces)

 \`\`\`<2 spaces>
Error  
Goes  
Here  
\`\`\`

**Comment by DeathRisings** [comment]
Thank You for spending your time looking at this.

 

Ron

**Comment by Tetsemi** [comment]
Here's what I'm getting

```
1x .../MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua:1: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name MinimapButtonFrame. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
[string "=[C]"]: in function `GetAddOnMetadata'
[string "@MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1: in main chunk

Locals:
(*temporary) = "MinimapButtonFrame"
(*temporary) = "Version"
(*temporary) = "Invalid AddOn name MinimapButtonFrame. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable)"
```

```
1x ...ceMinimapButtonFrameRedux_SkinPack/Skins.lua:5: attempt to call global 'MBFAddSkin' (a nil value)
[string "@MinimapButtonFrameRedux_SkinPack/Skins.lua"]:5: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "Hello Kitty"
(*temporary) = "Interface\AddOns\MinimapButtonFrameRedux_SkinPack\Textures\HKittyActive.tga"
(*temporary) = "Interface\AddOns\MinimapButtonFrameRedux_SkinPack\Textures\HKittyActiveBackdrop.tga"
(*temporary) = 35
(*temporary) = "attempt to call global 'MBFAddSkin' (a nil value)"
```

**Comment by Tetsemi** [comment]
That's it, the addon name is wrong in the first line.

`MBFversion = GetAddOnMetadata("MinimapButtonFrame", "Version");`

should be

`MBFversion = GetAddOnMetadata("MinimapButtonFrameRedux", "Version");`

in the MinimapButtonFrameRedux.lua

**Comment by karpana** [comment]
> 

works like a charm Tetsemi!
Thank you to you and all those who helped diagnose/debug this issue.

**Comment by Ketrel** [comment]
Tetsemi, your error appears to be a 10.1 compatiblity issue.

I have not yet had any time to work on this addon.  If that's the only issue I'll try to push a fix out tonight or tomorrow, but I'm dealing with a death in the family at the moment, and I'm not sure how focused I can be.

I've opened #16 to track this specifically

**Comment by Tetsemi** [comment]
> Tetsemi, your error appears to be a 10.1 compatiblity issue.
> 
> I have not yet had any time to work on this addon. If that's the only issue I'll try to push a fix out tonight or tomorrow, but I'm dealing with a death in the family at the moment, and I'm not sure how focused I can be.
> 
> I've opened #16 to track this specifically

I am so sorry for your loss, glad I could help out with the 10.1 issue.

**Comment by Ketrel** [comment]
Is this still happening as of the 10.1 versions?  (v3.2.2 or higher)?

**Comment by Ketrel** [comment]
I cannot reproduce this, and haven't seen anyone else report this.

**Comment by DeathRisings** [comment]
Thanks so much it works perfectly!
