### ISSUE TITLE
buttons wont group since ace 3 update

### ISSUE THREAD

**Issue by Yuno951** [Ketrel/MinimapButtonFrame-Redux#18]
![image](https://github.com/Ketrel/MinimapButtonFrame-Redux/assets/130261196/954dc96d-9b3b-464d-8832-258a7ae00dfe)

**Comment by Yuno951** [comment]
the box in the top right is the button frame when i close it the buttons disappear 
![image](https://github.com/Ketrel/MinimapButtonFrame-Redux/assets/130261196/ab0e0b73-bc04-4baa-af7c-731b9c5e337c)

**Comment by Ketrel** [comment]
What version of Ace3 is causing this?  
I'm using Release-r1320 locally for testing, and I can't reproduce this.  

Are you seeing any Lua errors?

**Comment by Yuno951** [comment]
![image](https://github.com/Ketrel/MinimapButtonFrame-Redux/assets/130261196/3fcece5f-6b1f-495c-aef4-69076ff244c9)
what ever the latest version and thats the only error im getting

**Comment by Ketrel** [comment]
Hmm, I don't think this is a problem with Ace or MBF.  I looked at what's happening at 1077 and it's just trying to turn to lowercase the name of all the frames, but its getting passed a frame with nil for the name.  

I think I can add a check to work around this issue, but I don't believe something's supposed to be creating minimap buttons with nil frame names.

I'll look into the best way to work around this, but without something triggering it, it's not going to be easy to test, so if you could by any chance let me know which addon is doing that, I can install that and see how best to fix.  I'm thinking I should just return false if its nil, but I need to double check.

**Comment by Yuno951** [comment]
maybe elvui latest update then? 

EDIT: yea just disabled elvui and it fixed itself 

would like to be able to use both :D

**Comment by Ketrel** [comment]
It does appear to be elvui.

It will be a moment before I can get this updated, but I found what should work with a quick test.

On line 1077 of MinimapButtonFrameRedux.lua change

```lua
if (strlower(v) == strlower(frameName)) then  
```
to  
```lua
if frameName ~= nil and (strlower(v) == strlower(frameName)) then
```

I gotta do a TOC bump release which I'll put that in when I do... soonish, but if you make that edit to your copy, you should be good.

**Comment by Ketrel** [comment]
Please let me know if that change fixes it for you

**Comment by Yuno951** [comment]
Ya sorry I went to sleep and changed it when I woke up forgot to reply here that the change fixed the issue
