### ISSUE TITLE
will this be updated for the war within?

### ISSUE THREAD

**Issue by Yuno951** [Ketrel/MinimapButtonFrame-Redux#19]
addon currently doesnt work , and was wondering if i should try and find a replacement or wait for an update

**Comment by Ketrel** [comment]
11.0.0 just released today and I wasn't even aware the realms were up yet.

I use this myself, so yes it will be updated.

**Comment by Yuno951** [comment]
lol sorry i didnt mean any harm, no rush or anything was just checking to see if it would be updated is all thank you for your work i love the addon

**Comment by cwwood0322** [comment]
Looking forward to the update.

**Comment by Ketrel** [comment]
I can't do anything until tomorrow but I think I see what might be wrong

**Comment by Ketrel** [comment]
Should be fixed with c1a6ed5de
