### ISSUE TITLE
Any plans to make this available for classic

### ISSUE THREAD

**Issue by Ravenslair38** [Ketrel/MinimapButtonFrame-Redux#2]
As my title asks since you are not the original author and i'm not sure if you want to take the time it would entail to make the modification to make this compatible with WOTLK classic. Should you decide to go forward with doing so i know there are many myself among them who would be very grateful. I had used MMBF as my main source of button management from its inception until i quite playing about the same time it became abandoned by its original author.

**Comment by Ketrel** [comment]
I don't personally play classic so I don't really have a way to test it.

However, if I recall, I used this way back in Wrath of the Lich King originally so an old version of the original addon from that era may work in classic.

(I'm on info blackout about Dragonflight, but I may have seen something about features of this addon being included, and if that's the case, I'm not even sure what if any updates I'll be doing to this at all.)

**Comment by Ketrel** [comment]
I don't play classic.  If someone wants to volunteer to maintain a classic version I'm game, otherwise, I cannot.
