### ISSUE TITLE
Issues in V10.0 - Dragonflight pre-patch

### ISSUE THREAD

**Issue by flashfire78** [Ketrel/MinimapButtonFrame-Redux#3]
In WoW v10.0 MinimapButtonFrame is no longer working. The window does not contain any buttons (see attachment) and bug grabber is getting the following errors:

7x Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.xml:9 Unrecognized XML: EdgeSize

7x Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.xml:8 Unrecognized XML attribute: tile

7x Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.xml:8 Unrecognized XML attribute: edgeFile

7x Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.xml:8 Unrecognized XML attribute: bgFile

8x Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.xml:8 Unrecognized XML: Backdrop

![mbf](https://user-images.githubusercontent.com/4294729/198333203-9bdfd01a-f7df-4ff6-8f71-5a959672cd11.jpg)

**Comment by Ketrel** [comment]
I have not yet had a chance to update any of my addons for DF.

I'm aware that it's currently broken and will likely be starting around Monday.

(I depend on this addon myself so I feel every bit of pain here .)

**Comment by Ketrel** [comment]
[Version 2.0.1](https://github.com/Ketrel/MinimapButtonFrame-Redux/releases/tag/v2.0.1)  
https://github.com/Ketrel/MinimapButtonFrame-Redux/releases/tag/v2.0.1

Fixes this issue.
