### ISSUE TITLE
v2.0.1 throwing up a LUA error

### ISSUE THREAD

**Issue by karpana** [Ketrel/MinimapButtonFrame-Redux#5]
I haven't quite figured out what's causing this, but this error is being thrown in my LUA error trapper.

```
Message: bad argument #2 to '?' (Usage: self:SetParent([parent]))
Time: Mon Oct 31 10:00:19 2022
Count: 1
Stack: bad argument #2 to '?' (Usage: self:SetParent([parent]))
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetParent'
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1538: in function `restoreButtonSettings'
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1611: in function `removeInvisible'
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1689: in function <.../MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua:1673>
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1749: in function `updatePositions'
[string "@Interface/AddOns/MinimapButtonFrameRedux/MinimapButtonFrameRedux.lua"]:1844: in function `?'
[string "@Interface/AddOns/AnnounceRare/Libraries/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...nceRare/Libraries/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: 
```

**Comment by karpana** [comment]
I think I've located the issue in terms of what action is causing this....

removing a TomTom waypoint causes the above noted issue to crop up.

**Comment by Ketrel** [comment]
I wasn't able to reproduce this with TomTom v3.3.2-release and MBF-R 2.0.1 or 2.0.2.

Are you using the same version of TomTom?

**Comment by karpana** [comment]
I'm also use TomTom v3.3.2, as well as a number of other addons, SexyMap being where I mainly see this.
I'll have to do an addon-by-addon test sweep to figure out where the incompatibility is showing up...

**Comment by Ketrel** [comment]
Can't just be a combo of those as I use SexyMap myself as well.

How are you removing the arrow, just right clicking the floating arrow?  Which option did you use to remove it?

**Comment by karpana** [comment]
I've just installed v2.0.3 and this issue seems to have gone away. 
probably resovled with the resolution of #4 via v2.0.2
