### ISSUE TITLE
Chat commands don't work

### ISSUE THREAD

**Issue by cwwood0322** [Ketrel/MinimapButtonFrame-Redux#6]
Cannot use chat commands to remove buttons gathered. Like the Covenant Sanctum/BFA Mission Board/ Legion Class Hall/ Garrison button. Same button for 4 xpacs but cannot be removed.

**Comment by cwwood0322** [comment]
Could be conficting with the SexyMap addon.

**Comment by Ketrel** [comment]
The button you're referring to is called `ExpansionLandingPageMinimapButton`

I intentionally did not exempt that from being gathered as I figured some people may want it to be.
If you want to stop it, add the name above to 'Protected Items' in the exceptions in settings, and then give your UI a reload.

I will look into if there's an issue with the command adding it.  I haven't used it personally in a while, but it should be adding it to that list when you remove it with the command.  Should be easy enough to fix if that's all that's broken.

**Comment by Ketrel** [comment]
I found the issue.  Pain in the rear, but simple fix.  I'll have a 2.0.3 out soon.

**Comment by Ketrel** [comment]
10.0.0 had broken this.

Now corrected in [v2.0.3](https://github.com/Ketrel/MinimapButtonFrame-Redux/releases/tag/v2.0.3)
