### ISSUE TITLE
Issues with icons

### ISSUE THREAD

**Issue by Dranni21312** [Ketrel/MinimapButtonFrame-Redux#8]
- The new tracking icon is not being collected by MBF

![image](https://user-images.githubusercontent.com/80227585/199643467-127a6199-5e86-4e60-ba6d-8817f5588cf3.png)

The "hide tracking" option also does not seem to work. 

- Zoom buttons are not displayed on minimap no matter if "Hide Zoom Buttons" option is enabled or not
- The calendar icon has a ring around it, and since the design of it has changed to square, it can probably be excluded from the decoration or somehow rescaled:

![image](https://user-images.githubusercontent.com/80227585/199643669-648d7f43-ea87-42a2-bd13-d2c4a01c1c36.png)

Thank you for all your work!

**Comment by Ketrel** [comment]
I can't reproduce what you're saying about the zoom buttons after 2.0.4
(However I did notice they only show on hover by default now)

I'll look into if I can remove the decoration on gathered buttons.

**Comment by Ketrel** [comment]
I'm still unable to reproduce the zoom button issue.
